#!/bin/sh

set -eu
[ -t 1 ] && set -x

APIKEY=$(cat ~/.priv/pw/clublog-api-key)

mkdir -p data

curl -sf -o data/clublog.xml.gz https://cdn.clublog.org/cty.php?api=$APIKEY
gunzip -f data/clublog.xml.gz
