#!/usr/bin/python3

from rrlog import country
import psycopg2

conn = psycopg2.connect('dbname=rrdxa')
cur = conn.cursor()

i = 0

while True:
    cur.execute("select start, call from log where dxcc is null limit 1")
    try:
        start, call = cur.fetchone()
    except:
        break
    dxcc = country.lookup(call, start)
    print(start, call, dxcc)
    cur.execute("update log set dxcc = %s where start between %s-'1 week'::interval and %s+'1 week'::interval and call = %s",
                [dxcc or 0, start, start, call])
    i += 1
    if i % 100 == 0:
        conn.commit()

conn.commit()
