# Generated by Django 4.2.30 on 2026-05-15 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                ("call", models.CharField(primary_key=True, serialize=False)),
                ("callsigns", models.CharField()),
                ("member_no", models.IntegerField()),
                ("display_name", models.CharField()),
                ("first_name", models.CharField()),
                ("last_name", models.CharField()),
                ("nickname", models.CharField()),
                ("user_email", models.CharField()),
                ("user_pass", models.CharField()),
                ("wpid", models.IntegerField()),
                ("user_roles", models.CharField()),
                ("public", models.BooleanField()),
                ("admin", models.BooleanField()),
            ],
            options={
                "db_table": "members",
                "ordering": ("call",),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vereinsmitglied",
            fields=[
                ("member_no", models.IntegerField(primary_key=True, serialize=False)),
                ("call", models.CharField()),
                ("display_name", models.CharField()),
                ("account_created", models.DateField(auto_now_add=True)),
                ("vereinsbeitritt", models.DateField(blank=True, null=True)),
                ("bezahlt_bis", models.DateField(blank=True, null=True)),
                ("vereinsaustritt", models.DateField(blank=True, null=True)),
                ("silent_key", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "verein",
                "ordering": ("call",),
            },
        ),
    ]
