# Generated by Django 5.2.15 on 2026-07-07 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrmember", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                ("betreff", models.CharField(max_length=1000)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrmember.vereinsmitglied",
                    ),
                ),
            ],
            options={
                "db_table": "verein_zahlung",
                "ordering": ("datum", "mitglied"),
            },
        ),
    ]
