# Generated by Django 4.2.30 on 2026-05-15 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rrmember", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zahlung",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datum", models.DateField()),
                ("betrag", models.DecimalField(decimal_places=2, max_digits=10)),
                ("betreff", models.CharField(max_length=1000)),
                (
                    "mitglied",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="rrmember.vereinsmitglied",
                    ),
                ),
            ],
        ),
    ]
