# Generated by Django 4.2.27 on 2026-01-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField()),
                ('cabrillo_name', models.CharField()),
                ('event', models.CharField()),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField()),
                ('author', models.CharField()),
                ('created', models.DateTimeField()),
                ('vhf', models.BooleanField()),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
