#!/usr/bin/python3

import argparse
import psycopg
from psycopg.rows import namedtuple_row
from email.message import EmailMessage
from email.headerregistry import Address
import smtplib

argparser = argparse.ArgumentParser(description="Send the RRDXA DX Challenge status mail")
argparser.add_argument("-m", "--mail")
args = argparser.parse_args()

conn = psycopg.connect("service=rrdxa", autocommit=False)
cur = conn.cursor(row_factory=namedtuple_row)

cur.execute("select current_date")
[today] = cur.fetchone()

txt = f"RRDXA DX Challenge Stand {today}"

q = """
select coalesce(major_mode::text, 'MIXED') as major_mode, rrmember, bandslots, rank() over (partition by major_mode order by bandslots desc) from
(select major_mode, rrmember, count(distinct (band, dxcc)) as bandslots
    from bandpoints
    where year = extract(year from now())
    group by grouping sets ((1, 2), (2)));
"""
cur.execute(q)
mode = None
for row in cur.fetchall():
    if row.major_mode != mode:
        mode = row.major_mode
        n = 0
        txt += f"\n\n{mode}:\n"
    if n % 5 == 0:
        txt += "  "
    txt += f"{row.rank:3} {row.rrmember:6} {row.bandslots:4}  "
    if n % 5 == 4:
        txt += "\n"
    n += 1
txt += "\n\nhttps://logbook.rrdxa.org/dxchallenge/\n"

# send it
if args.mail:
    msg = EmailMessage()
    msg['From'] = Address(display_name=f"RRDXA DX Challenge",  addr_spec="noreply@rrdxa.org")
    msg['Reply-To'] = Address(display_name=f"RRDXA",  addr_spec="rrdxa@mailman.qth.net")
    msg['To'] = Address(display_name=f"RRDXA", addr_spec="rrdxa@mailman.qth.net")
    msg['Subject'] = f"DX Challenge {today}"
    msg.set_content(txt)
    with smtplib.SMTP('localhost') as smtp:
        smtp.send_message(msg)

else:
    print(txt)
