#!/usr/bin/python3

import psycopg
from psycopg.rows import namedtuple_row
from email.message import EmailMessage
from email.headerregistry import Address
import smtplib

conn = psycopg.connect("service=rrdxa", autocommit=False)
cur = conn.cursor(row_factory=namedtuple_row)

def format_ops(ops):
    msg = ""
    for op in ops:
        msg += f"        {op['rrmember']}"
        if op['station_callsign'] and op['station_callsign'] != op['rrmember']:
            msg += f" ({op['station_callsign']})"
        if op['operator'] and op['operator'] != op['rrmember']:
            msg += f" ({op['operator']})"
        msg += f" {op['start']} {op['band']} {op['mode']}"
        if op['submode']:
            msg += f" {op['submode']}"
        msg += f" {op['call']}\n"
    return msg + "\n"

msg = "RRDXA DX Challenge\n\n"

q = """
select major_mode, country, array_agg(row_to_json(b)) as ops from bandpoints b
    join dxcc on b.dxcc = dxcc.dxcc
    where year = extract(year from 'yesterday'::date) and
    not exists (select from previous_bandpoints pb where b.major_mode = pb.major_mode and b.dxcc = pb.dxcc and year = extract(year from 'yesterday'::date))
    group by major_mode, country
    order by major_mode, country;
"""
cur.execute(q)
if cur.rowcount > 0:
    msg += "Neue 2024-ATNO:\n\n"
    for row in cur.fetchall():
        msg += f"    {row.major_mode}: {row.country.title()}\n"
        msg += format_ops(row.ops)

q = """
select major_mode, country, band, array_agg(row_to_json(b)) as ops from bandpoints b
    join dxcc on b.dxcc = dxcc.dxcc
    where year = extract(year from 'yesterday'::date) and
    not exists (select from previous_bandpoints pb where b.major_mode = pb.major_mode and b.dxcc = pb.dxcc and b.band = pb.band and year = extract(year from 'yesterday'::date))
    group by major_mode, band, country
    order by major_mode, band, country;
"""
cur.execute(q)
if cur.rowcount > 0:
    msg += "Neue Bandslots:\n\n"
    for row in cur.fetchall():
        msg += f"    {row.major_mode} {row.band}: {row.country.title()}\n"
        msg += format_ops(row.ops)

#\echo New DXers
#select major_mode, rrmember, array_agg(row_to_json(b)) from bandpoints b
#    where year = extract(year from 'yesterday'::date) and
#    not exists (select from previous_bandpoints pb where b.major_mode = pb.major_mode and b.rrmember = pb.rrmember and year = extract(year from 'yesterday'::date))
#    group by major_mode, rrmember;
#
#\echo Most wanted countries
#select major_mode, dxcc, count(*) from bandpoints group by major_mode, dxcc order by major_mode, count(*), dxcc;
#
#\echo Most wanted bandslots
#select major_mode, dxcc, band, count(*) from bandpoints group by major_mode, dxcc, band order by major_mode, count(*), dxcc, band;
#
#\echo Bandpoints gained
#select major_mode, rrmember, dxcc, band, array_agg(row_to_json(b)) from bandpoints b
#    where year = extract(year from 'yesterday'::date) and
#    not exists (select from previous_bandpoints pb where b.major_mode = pb.major_mode and b.rrmember = pb.rrmember and b.dxcc = pb.dxcc and b.band = pb.band and year = extract(year from 'yesterday'::date))
#    group by major_mode, rrmember, dxcc, band;
#

cur.execute("""
delete from previous_bandpoints;
insert into previous_bandpoints select * from bandpoints;

insert into bandpoints_history
select 'yesterday'::date, *, rank() over (partition by major_mode, band order by count desc) from
(select rrmember, major_mode, band, count(distinct dxcc), array_agg(distinct dxcc)
    from bandpoints
    where year = extract(year from 'yesterday'::date)
    group by grouping sets((rrmember, major_mode), (rrmember, major_mode, band)));
""")

conn.commit()

print(msg)

#
#    # send it
#    if send:
#        msg = EmailMessage()
#        msg['From'] = Address(display_name=f"{data.uploader} via rrdxa.org",  addr_spec="logbook@rrdxa.org")
#        msg['To'] = Address(display_name=f"{data.contest} score submission", addr_spec="rrdxa@mailman.qth.net")
#        msg['Subject'] = subject
#        msg['X-Callsign'] = data.station_callsign
#        msg['X-Contest'] = data.contest
#        msg.set_content(mail)
#        with smtplib.SMTP('localhost') as smtp:
#            smtp.send_message(msg)
#
