"""
Django settings for rrdxa project.

Generated by 'django-admin startproject' using Django 3.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v%%kw28nw6d6z&v%s$6e^*)6^e*x*wfb5e85-9es*dq+-f83x$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['logbook.rrdxa.org', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    #'daphne',
    #'channels',
    #'channels_postgres',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.messages',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.humanize',
    'django.contrib.staticfiles',
    'api',
    #'cluster',
    'contestchallenge',
    'dxchallenge',
    'rrlog',
    'rrmember',
    'vorstand',
]

# OIDC RP. The package is installed under the user site-packages dir
# (pip install --user mozilla-django-oidc) because apt does not package
# it. We always import the app so management commands like
# `manage.py shell` can still resolve OIDC_* settings without crashing
# — the actual backend selection is gated on OIDC_ENABLED below.
INSTALLED_APPS += ['mozilla_django_oidc']

MIDDLEWARE = [
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware', # breaks log uploads
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Re-auths users silently via prompt=none once the id_token expires.
    # Without this, users get bumped every hour (id_token lifetime).
    # See AGENTS.md "Phase 2 — step 7".
    'mozilla_django_oidc.middleware.SessionRefresh',
]

# --- Authentication backend selection ---
#
# OIDC_ENABLED flips between the legacy WordpressAuthBackend (which
# verifies passwords against WP's user_pass column via passlib) and the
# OIDC RP. The legacy backend stays installed while OIDC_ENABLED=False
# so we can roll back without redeploying. Phase 3 removes
# WordpressAuthBackend entirely; see AGENTS.md.
#
# TODO Phase 3: hardcode OIDCRPAuthenticationBackend here, delete
# rrmember/auth.py's WordpressAuthBackend class, drop the passlib
# dependency.
OIDC_ENABLED = False

if OIDC_ENABLED:
    AUTHENTICATION_BACKENDS = [
        "rrmember.oidc_auth.OIDCRPAuthenticationBackend",
    ]
else:
    AUTHENTICATION_BACKENDS = [
        "rrmember.auth.WordpressAuthBackend",
    ]

# --- OIDC RP settings ---
#
# Only consulted when OIDC_ENABLED=True. Kept here (rather than gated)
# so `manage.py check` can validate the values regardless of the flag.
#
# `mozilla-django-oidc` does NOT auto-discover from the IdP's discovery
# doc — every OIDC_OP_* endpoint must be set explicitly. The discovery
# doc advertises authorization_endpoint = /wp-json/openid-connect/authorize
# but the actual browser flow uses wp-login.php?action=openid-authenticate
# (WP needs an authenticated session before authorizing the client).
#
# Quirks documented in AGENTS.md "Tier-2 quirks":
# - scopes_supported = ["openid", "profile"] — no "email" scope, plugin
#   does not emit email claim; OIDC_RP_SCOPES does NOT request email.
# - JWKS omits "kid"; OIDC_VERIFY_KID=False skips the kid-check loop in
#   mozilla_django_oidc.auth.retrieve_matching_jwk.
if OIDC_ENABLED:
    OIDC_RP_CLIENT_ID = "logbook.rrdxa.org"
    # Must match OIDC_LOGBOOK_WEB_SECRET in wp-config.php. Set in
    # /etc/logbook.rrdxa.org/oidc.env (chmod 0640, owner=myon:www-data)
    # and read here at startup. See deploy notes — not yet deployed.
    OIDC_RP_CLIENT_SECRET = "REPLACE_ME_AT_DEPLOY_TIME"
    OIDC_RP_SIGN_ALGO = "RS256"

    OIDC_OP_AUTHORIZATION_ENDPOINT = "https://rrdxa.org/wp-json/openid-connect/authorize"
    OIDC_OP_TOKEN_ENDPOINT         = "https://rrdxa.org/wp-json/openid-connect/token"
    OIDC_OP_USER_ENDPOINT          = "https://rrdxa.org/wp-json/openid-connect/userinfo"
    OIDC_OP_JWKS_ENDPOINT          = "https://rrdxa.org/.well-known/jwks.json"

    OIDC_RP_SCOPES = "openid profile"
    OIDC_VERIFY_KID = False

    OIDC_USE_NONCE = True
    OIDC_USE_PKCE = True
    OIDC_CREATE_USER = True

    LOGIN_REDIRECT_URL = "/"
    LOGIN_REDIRECT_URL_FAILURE = "/login-failed/"
    # ``redirect_to_login`` (used by ``auth_required`` when a browser hits
    # a member view without an OIDC session) needs this to point at the
    # mozilla-django-oidc login trigger. Hardcoded to match the path that
    # ``path('oidc/', include('mozilla_django_oidc.urls'))`` mounts.
    # Keeping it aligned also means any future @login_required use on a
    # view Just Works.
    LOGIN_URL = "/oidc/authenticate/"

ROOT_URLCONF = 'rrdxa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'rrdxa.wsgi.application'
ASGI_APPLICATION = "rrdxa.asgi.application"

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'rrdxa',
    },
    #'channels_postgres': {
    #    'ENGINE': 'django.db.backends.postgresql',
    #    'NAME': 'rrdxa',
    #},
}

CHANNEL_LAYERS = {
    'default': {
        #'BACKEND': 'channels_postgres.core.PostgresChannelLayer',
        #'CONFIG': {
        #    'ENGINE': 'django.db.backends.postgresql',
        #    'NAME': 'rrdxa',
        #    'config': {
        #    }
        #},
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
LANGUAGE_CODE = 'de-de'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = False # use *_FORMAT instead
USE_TZ = True
DATE_FORMAT = "d.m.Y"
SHORT_DATETIME_FORMAT = "d.m.Y H:i"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# people who can edit other people's uploads
RRDXA_ADMINS = [
        'DF7CB',
        'DF7EE',
        'DK2DQ',
        'DL9DAN',
        ]

JAHRESBEITRAG = 12.0
